[package]
name = "onair-obs"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
onair-core = { path = "../onair-core" }

opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
